### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by itzL0g4n** [philhk/discord-name-sniper#1]
i have node.js v16 installed, but seems like it's the program can't open up. It's just instantly close by it self

**Comment by philhk** [comment]
Yes, I thought that would happen at some point. This is actually completely normal and by the way you don't need NodeJS for the exe. What happens here is that a config file is created in the exe's directory and there are no accounts in it, so the exe just closes with the message ´You didn't add any accounts. Was that a mistake?´ but you won't see it because for some reason the console will close immediately. To fix the problem just search for config.json and add some accounts. For clarity I'll try to update it so the console stays open even if there is no account.
